Models/Setter.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admission.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setter
    {
        public int Se_Id { get; set; }
        public string Se_Name { get; set; }
        public string Se_Email { get; set; }
    }
}

Controllers/SetterController.cs
using Admission.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Admission.Controllers
{
    public class SetterController : Controller
    {
        // GET: Setter
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(QuestionViewModel ques)
        {
            try
                {
                    if (ModelState.IsValid)
                    {
                        using (Varsity_Admission db = new Varsity_Admission())
                        {
                            Question question = new Question();
                            question.E_Year = ques.E_Year;
                            question.Q_Body = ques.Q_Body;
                            question.Op_1 = ques.Op_1;
                            question.Op_2 = ques.Op_2;
                            question.Op_3 = ques.Op_3;
                            question.Op_4 = ques.Op_4;
                            question.Op_5 = ques.Op_5;
                            question.Q_Answer = ques.Q_Answer;

                            db.Questions.Add(question);
                            db.SaveChanges();

                            ViewBag.success_insert = "Data inserted successfully";
                            ModelState.Clear();
                            return View();
                        }
                    }
                }
                catch (Exception e)
                {
                    throw e;
                }

            
            return View();
            
        }

        public ActionResult SeeYear()
        {
            //Varsity_Admission examEntity = new Varsity_Admission();
            //var getYear = examEntity.Exams.ToList();
            //SelectList list = new SelectList(getYear, "E_Id", "E_Year");
            //ViewBag.year = list;
            return View();

            
        }

        [HttpPost]
        public ActionResult SeeYear(int? year)
        {
            try
            {
                
                    if (year == null)
                    {
                        ViewBag.error = "Invalid Request !";
                    }
                    else
                        return RedirectToAction("SeeQues", new { Id = year });
                    //ModelState.Clear();
                    // ViewBag.error.clear();

            }
            catch (Exception e)
            {
                throw e;
                //ViewBag.err = "Error !";
            }

            return View();
        }

        public ActionResult SeeQues(int id)
        {
            
            Varsity_Admission queEntity = new Varsity_Admission();

            var ques = queEntity.Questions
               .Where(q => q.E_Year == id);

            var queList = ques.ToList();
            if(!queList.Any())
            {
                ViewBag.empty = "No Data Found! ";
            }
            return View(queList);
        }

        public ActionResult Edit(int? id)
        {
            Varsity_Admission queEntity = new Varsity_Admission();
            Question que = queEntity.Questions.Find(id);
            return View(que);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Q_Id,E_Year,Q_Body,Op_1,Op_2,Op_3,Op_4,Op_5,Q_Answer")] Question qstn)
        {
            Varsity_Admission queEntity = new Varsity_Admission();
            int yr;
            if (ModelState.IsValid)
            {
                queEntity.Entry(qstn).State = EntityState.Modified;
                queEntity.SaveChanges();
                yr = qstn.E_Year;
                return RedirectToAction("SeeQues", new { Id = yr });
            }
            //  return View(prson);
            else
            {
                return View();
            }

        }


        public ActionResult Delete(int? id)
        {
            Varsity_Admission queEntity = new Varsity_Admission();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Employee employee = db.Employees.Find(id);
            Question que = queEntity.Questions.Find(id);
            if (que == null)
            {
                return HttpNotFound();
            }
            return View(que);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Varsity_Admission queEntity = new Varsity_Admission();
            Question qs = queEntity.Questions.Find(id);
            int yr = qs.E_Year;
            queEntity.Questions.Remove(qs);
            queEntity.SaveChanges();
            return RedirectToAction("SeeQues", new { Id = yr });
            //return RedirectToAction("Index");
        }
    }
}

Views/Setter/Delete.cshtml
@model Admission.Models.Question

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.E_Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.E_Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Q_Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Q_Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Op_1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Op_1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Op_2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Op_2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Op_3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Op_3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Op_4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Op_4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Op_5)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Op_5)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Q_Answer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Q_Answer)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Setter/Edit.cshtml
@model Admission.Models.Question
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Q_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.E_Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.E_Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.E_Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Q_Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Q_Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Q_Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Op_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Op_1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Op_1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Op_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Op_2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Op_2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Op_3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Op_3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Op_3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Op_4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Op_4, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Op_4, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Op_5, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Op_5, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Op_5, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Q_Answer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Q_Answer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Q_Answer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Setter/Index.cshtml
@model Admission.Models.QuestionViewModel
@{
    Layout = null;
}
@{
    ViewBag.Title = "Index";
}

@*@if(Session["setterlogin"] == null)
{
    Response.Redirect("~/Login/Index");
}*@

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">
    <!-- Title Page-->
    <title>Online Admission - Setter</title>
    <!-- Icons font CSS-->
    <link href="~/Content/Register/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="~/Content/Register/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <!-- Vendor CSS-->
    <link href="~/Content/Register/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/Content/Register/vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">
    <!-- Main CSS-->
    <link href="~/Content/Register/css/main.css" rel="stylesheet" media="all">
    <link href="~/Content/Home/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">Online Admission</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Logout", "Login")">Logout</a>
                    </li>
                </ul>
            </div>

        </div>
    </nav>

    <div class="container">
        <br /><br /><br /> <br /> <br />
        <div class="card" style="width: 55rem;">
            <h2>Setter</h2>
            <div class="card-body">
                @if (Session["setter_name"] != null)
                {
                    <h3> <b> @Session["setter_name"] </b> </h3>
                }
                <form method="POST">
                    @if (ViewBag.success_insert != null)
                    {
                        <div class="text-success">@ViewBag.success_insert</div>
                    }
                    <div class="form-row">
                        <div class="name">Year</div>
                        <div class="value">
                            <div class="row">
                                <div class="col-4">
                                    <div class="input-group">
                                        @*<input class="input--style-5" type="text" name="Year">*@
                                        @Html.EditorFor(model => model.E_Year, new { htmlAttributes = new { @class = "input--style-5" } })
                                        @Html.ValidationMessageFor(model => model.E_Year, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="form-row">
                        <div class="name">Question Body</div>
                        <div class="value">
                            <div class="input-group">
                                @*<textarea rows="4" cols="100" name="qbody"></textarea>*@
                                @Html.EditorFor(model => model.Q_Body, new { htmlAttributes = new { @class = "input--style-5" } })
                                @Html.ValidationMessageFor(model => model.Q_Body, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="name">Option A</div>
                        <div class="value">
                            <div class="row">
                                <div class="col-4">
                                    <div class="input-group">
                                        @*<input class="input--style-5" type="text" name="a">*@
                                        @Html.EditorFor(model => model.Op_1, new { htmlAttributes = new { @class = "input--style-5" } })
                                        @Html.ValidationMessageFor(model => model.Op_1, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="form-row">
                        <div class="name">Option B</div>
                        <div class="value">
                            <div class="row">
                                <div class="col-4">
                                    <div class="input-group">
                                        @Html.EditorFor(model => model.Op_2, new { htmlAttributes = new { @class = "input--style-5" } })
                                        @Html.ValidationMessageFor(model => model.Op_2, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="form-row">
                        <div class="name">Option C</div>
                        <div class="value">
                            <div class="row">
                                <div class="col-4">
                                    <div class="input-group">
                                        @Html.EditorFor(model => model.Op_3, new { htmlAttributes = new { @class = "input--style-5" } })
                                        @Html.ValidationMessageFor(model => model.Op_3, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="form-row">
                        <div class="name">Option D</div>
                        <div class="value">
                            <div class="row">
                                <div class="col-4">
                                    <div class="input-group">
                                        @Html.EditorFor(model => model.Op_4, new { htmlAttributes = new { @class = "input--style-5" } })
                                        @Html.ValidationMessageFor(model => model.Op_4, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="form-row">
                        <div class="name">Option E</div>
                        <div class="value">
                            <div class="row">
                                <div class="col-4">
                                    <div class="input-group">
                                        @Html.EditorFor(model => model.Op_5, new { htmlAttributes = new { @class = "input--style-5" } })
                                        @Html.ValidationMessageFor(model => model.Op_5, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="form-row">
                        <div class="name">Correct Answer</div>
                        <div class="value">
                            <div class="row">
                                <div class="col-4">
                                    <div class="input-group">
                                        @Html.EditorFor(model => model.Q_Answer, new { htmlAttributes = new { @class = "input--style-5" } })
                                        @Html.ValidationMessageFor(model => model.Q_Answer, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div>
                        <button class="btn btn--radius-2 btn--red" type="submit">Insert</button>
                    </div>
                </form>
                @*@Html.DropDownList("year", ViewBag.year as SelectList, "--Select Year--")*@
            </div>
        </div>

        @*<div class="card" style="width: 55rem;">
            <div class="card-body">
                
            </div>

        </div>*@

    </div>
        <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br />  <br />
        <footer class="py-5 bg-dark">
            <div class="container">
                <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
            </div>
            <!-- /.container -->
        </footer>
        <script src="~/Content/Register/vendor/jquery/jquery.min.js"></script>
        <!-- Vendor JS-->
        <script src="~/Content/Register/vendor/select2/select2.min.js"></script>
        <script src="~/Content/Register/vendor/datepicker/moment.min.js"></script>
        <script src="~/Content/Register/vendor/datepicker/daterangepicker.js"></script>
        <!-- Main JS-->
        <script src="~/Content/Register/js/global.js"></script>

        <script src="~/Content/Home/vendor/jquery/jquery.min.js"></script>
</body>
</html>

Views/Setter/SeeQues.cshtml
@model IEnumerable<Admission.Models.Question>

@{
    ViewBag.Title = "SeeQues";
}

<h2>See Questions</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@

@if (ViewBag.empty != null)
{
    <div class="text-danger">@ViewBag.empty</div>
}

<table class="table">

    <tr>
        <th>
            @Html.DisplayNameFor(model => model.E_Year)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Q_Body)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Op_1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Op_2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Op_3)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Op_4)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Op_5)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Q_Answer)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.E_Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Q_Body)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Op_1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Op_2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Op_3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Op_4)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Op_5)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Q_Answer)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Q_Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Q_Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Q_Id })
            </td>
        </tr>
    }

</table>

Views/Setter/SeeYear.cshtml
@{
    ViewBag.Title = "SeeYear";
}


<div class="card" style="width: 55rem;">
    <div class="card-body">
        @using (Html.BeginForm("SeeYear", "Setter"))
        {
            @Html.AntiForgeryToken()
            @*if (ViewBag.error != null)
            {
                <div class="text-danger">@ViewBag.error</div>
            }*@



        <div class="form-horizontal">
            <h4>See and Edit Questions</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @if (ViewBag.error != null)
            {
            <div class="text-danger">@ViewBag.error</div>
            }
            <div class="form-group">
                <div class="col-md-10">
                    @*@Html.DropDownList("year", ViewBag.year as SelectList, "--Select Year--")*@
                    <input type="text" id="year" name="year" value="" />
                </div>
            </div>
            @*@Html.DropDownList("year", ViewBag.year as SelectList, "--Select Year--")*@
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Show" class="btn btn-default" />
                </div>
            </div>
        </div>

          }
    </div>

</div>

        